/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R9RouteImport } from './routes/9'
import { Route as R8RouteImport } from './routes/8'
import { Route as R7RouteImport } from './routes/7'
import { Route as R6RouteImport } from './routes/6'
import { Route as R5RouteImport } from './routes/5'
import { Route as R4RouteImport } from './routes/4'
import { Route as R3RouteImport } from './routes/3'
import { Route as R2RouteImport } from './routes/2'
import { Route as R15RouteImport } from './routes/15'
import { Route as R14RouteImport } from './routes/14'
import { Route as R13RouteImport } from './routes/13'
import { Route as R12RouteImport } from './routes/12'
import { Route as R11RouteImport } from './routes/11'
import { Route as R10RouteImport } from './routes/10'
import { Route as R1RouteImport } from './routes/1'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R9IndexRouteImport } from './routes/9.index'
import { Route as R8IndexRouteImport } from './routes/8.index'
import { Route as R7IndexRouteImport } from './routes/7.index'
import { Route as R6IndexRouteImport } from './routes/6.index'
import { Route as R5IndexRouteImport } from './routes/5.index'
import { Route as R4IndexRouteImport } from './routes/4.index'
import { Route as R3IndexRouteImport } from './routes/3.index'
import { Route as R2IndexRouteImport } from './routes/2.index'
import { Route as R10IndexRouteImport } from './routes/10.index'
import { Route as R1IndexRouteImport } from './routes/1.index'
import { Route as R9TodayRouteImport } from './routes/9.today'
import { Route as R9HistoryRouteImport } from './routes/9.history'
import { Route as R9DashboardRouteImport } from './routes/9.dashboard'
import { Route as R8TodayRouteImport } from './routes/8.today'
import { Route as R8HistoryRouteImport } from './routes/8.history'
import { Route as R8DashboardRouteImport } from './routes/8.dashboard'
import { Route as R7TodayRouteImport } from './routes/7.today'
import { Route as R7HistoryRouteImport } from './routes/7.history'
import { Route as R7DashboardRouteImport } from './routes/7.dashboard'
import { Route as R6TodayRouteImport } from './routes/6.today'
import { Route as R6HistoryRouteImport } from './routes/6.history'
import { Route as R6DashboardRouteImport } from './routes/6.dashboard'
import { Route as R5TodayRouteImport } from './routes/5.today'
import { Route as R5HistoryRouteImport } from './routes/5.history'
import { Route as R5DashboardRouteImport } from './routes/5.dashboard'
import { Route as R4TodayRouteImport } from './routes/4.today'
import { Route as R4HistoryRouteImport } from './routes/4.history'
import { Route as R4DashboardRouteImport } from './routes/4.dashboard'
import { Route as R3TodayRouteImport } from './routes/3.today'
import { Route as R3HistoryRouteImport } from './routes/3.history'
import { Route as R3DashboardRouteImport } from './routes/3.dashboard'
import { Route as R2TodayRouteImport } from './routes/2.today'
import { Route as R2HistoryRouteImport } from './routes/2.history'
import { Route as R2DashboardRouteImport } from './routes/2.dashboard'
import { Route as R10TodayRouteImport } from './routes/10.today'
import { Route as R10HistoryRouteImport } from './routes/10.history'
import { Route as R10DashboardRouteImport } from './routes/10.dashboard'
import { Route as R1TodayRouteImport } from './routes/1.today'
import { Route as R1HistoryRouteImport } from './routes/1.history'
import { Route as R1DashboardRouteImport } from './routes/1.dashboard'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R9Route = R9RouteImport.update({
  id: '/9',
  path: '/9',
  getParentRoute: () => rootRouteImport,
} as any)
const R8Route = R8RouteImport.update({
  id: '/8',
  path: '/8',
  getParentRoute: () => rootRouteImport,
} as any)
const R7Route = R7RouteImport.update({
  id: '/7',
  path: '/7',
  getParentRoute: () => rootRouteImport,
} as any)
const R6Route = R6RouteImport.update({
  id: '/6',
  path: '/6',
  getParentRoute: () => rootRouteImport,
} as any)
const R5Route = R5RouteImport.update({
  id: '/5',
  path: '/5',
  getParentRoute: () => rootRouteImport,
} as any)
const R4Route = R4RouteImport.update({
  id: '/4',
  path: '/4',
  getParentRoute: () => rootRouteImport,
} as any)
const R3Route = R3RouteImport.update({
  id: '/3',
  path: '/3',
  getParentRoute: () => rootRouteImport,
} as any)
const R2Route = R2RouteImport.update({
  id: '/2',
  path: '/2',
  getParentRoute: () => rootRouteImport,
} as any)
const R15Route = R15RouteImport.update({
  id: '/15',
  path: '/15',
  getParentRoute: () => rootRouteImport,
} as any)
const R14Route = R14RouteImport.update({
  id: '/14',
  path: '/14',
  getParentRoute: () => rootRouteImport,
} as any)
const R13Route = R13RouteImport.update({
  id: '/13',
  path: '/13',
  getParentRoute: () => rootRouteImport,
} as any)
const R12Route = R12RouteImport.update({
  id: '/12',
  path: '/12',
  getParentRoute: () => rootRouteImport,
} as any)
const R11Route = R11RouteImport.update({
  id: '/11',
  path: '/11',
  getParentRoute: () => rootRouteImport,
} as any)
const R10Route = R10RouteImport.update({
  id: '/10',
  path: '/10',
  getParentRoute: () => rootRouteImport,
} as any)
const R1Route = R1RouteImport.update({
  id: '/1',
  path: '/1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R9IndexRoute = R9IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => R9Route,
} as any)
const R8IndexRoute = R8IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => R8Route,
} as any)
const R7IndexRoute = R7IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => R7Route,
} as any)
const R6IndexRoute = R6IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => R6Route,
} as any)
const R5IndexRoute = R5IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => R5Route,
} as any)
const R4IndexRoute = R4IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => R4Route,
} as any)
const R3IndexRoute = R3IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => R3Route,
} as any)
const R2IndexRoute = R2IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => R2Route,
} as any)
const R10IndexRoute = R10IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => R10Route,
} as any)
const R1IndexRoute = R1IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => R1Route,
} as any)
const R9TodayRoute = R9TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => R9Route,
} as any)
const R9HistoryRoute = R9HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => R9Route,
} as any)
const R9DashboardRoute = R9DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => R9Route,
} as any)
const R8TodayRoute = R8TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => R8Route,
} as any)
const R8HistoryRoute = R8HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => R8Route,
} as any)
const R8DashboardRoute = R8DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => R8Route,
} as any)
const R7TodayRoute = R7TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => R7Route,
} as any)
const R7HistoryRoute = R7HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => R7Route,
} as any)
const R7DashboardRoute = R7DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => R7Route,
} as any)
const R6TodayRoute = R6TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => R6Route,
} as any)
const R6HistoryRoute = R6HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => R6Route,
} as any)
const R6DashboardRoute = R6DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => R6Route,
} as any)
const R5TodayRoute = R5TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => R5Route,
} as any)
const R5HistoryRoute = R5HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => R5Route,
} as any)
const R5DashboardRoute = R5DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => R5Route,
} as any)
const R4TodayRoute = R4TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => R4Route,
} as any)
const R4HistoryRoute = R4HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => R4Route,
} as any)
const R4DashboardRoute = R4DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => R4Route,
} as any)
const R3TodayRoute = R3TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => R3Route,
} as any)
const R3HistoryRoute = R3HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => R3Route,
} as any)
const R3DashboardRoute = R3DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => R3Route,
} as any)
const R2TodayRoute = R2TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => R2Route,
} as any)
const R2HistoryRoute = R2HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => R2Route,
} as any)
const R2DashboardRoute = R2DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => R2Route,
} as any)
const R10TodayRoute = R10TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => R10Route,
} as any)
const R10HistoryRoute = R10HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => R10Route,
} as any)
const R10DashboardRoute = R10DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => R10Route,
} as any)
const R1TodayRoute = R1TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => R1Route,
} as any)
const R1HistoryRoute = R1HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => R1Route,
} as any)
const R1DashboardRoute = R1DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => R1Route,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/1': typeof R1RouteWithChildren
  '/10': typeof R10RouteWithChildren
  '/11': typeof R11Route
  '/12': typeof R12Route
  '/13': typeof R13Route
  '/14': typeof R14Route
  '/15': typeof R15Route
  '/2': typeof R2RouteWithChildren
  '/3': typeof R3RouteWithChildren
  '/4': typeof R4RouteWithChildren
  '/5': typeof R5RouteWithChildren
  '/6': typeof R6RouteWithChildren
  '/7': typeof R7RouteWithChildren
  '/8': typeof R8RouteWithChildren
  '/9': typeof R9RouteWithChildren
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/1/dashboard': typeof R1DashboardRoute
  '/1/history': typeof R1HistoryRoute
  '/1/today': typeof R1TodayRoute
  '/10/dashboard': typeof R10DashboardRoute
  '/10/history': typeof R10HistoryRoute
  '/10/today': typeof R10TodayRoute
  '/2/dashboard': typeof R2DashboardRoute
  '/2/history': typeof R2HistoryRoute
  '/2/today': typeof R2TodayRoute
  '/3/dashboard': typeof R3DashboardRoute
  '/3/history': typeof R3HistoryRoute
  '/3/today': typeof R3TodayRoute
  '/4/dashboard': typeof R4DashboardRoute
  '/4/history': typeof R4HistoryRoute
  '/4/today': typeof R4TodayRoute
  '/5/dashboard': typeof R5DashboardRoute
  '/5/history': typeof R5HistoryRoute
  '/5/today': typeof R5TodayRoute
  '/6/dashboard': typeof R6DashboardRoute
  '/6/history': typeof R6HistoryRoute
  '/6/today': typeof R6TodayRoute
  '/7/dashboard': typeof R7DashboardRoute
  '/7/history': typeof R7HistoryRoute
  '/7/today': typeof R7TodayRoute
  '/8/dashboard': typeof R8DashboardRoute
  '/8/history': typeof R8HistoryRoute
  '/8/today': typeof R8TodayRoute
  '/9/dashboard': typeof R9DashboardRoute
  '/9/history': typeof R9HistoryRoute
  '/9/today': typeof R9TodayRoute
  '/1/': typeof R1IndexRoute
  '/10/': typeof R10IndexRoute
  '/2/': typeof R2IndexRoute
  '/3/': typeof R3IndexRoute
  '/4/': typeof R4IndexRoute
  '/5/': typeof R5IndexRoute
  '/6/': typeof R6IndexRoute
  '/7/': typeof R7IndexRoute
  '/8/': typeof R8IndexRoute
  '/9/': typeof R9IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/11': typeof R11Route
  '/12': typeof R12Route
  '/13': typeof R13Route
  '/14': typeof R14Route
  '/15': typeof R15Route
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/1/dashboard': typeof R1DashboardRoute
  '/1/history': typeof R1HistoryRoute
  '/1/today': typeof R1TodayRoute
  '/10/dashboard': typeof R10DashboardRoute
  '/10/history': typeof R10HistoryRoute
  '/10/today': typeof R10TodayRoute
  '/2/dashboard': typeof R2DashboardRoute
  '/2/history': typeof R2HistoryRoute
  '/2/today': typeof R2TodayRoute
  '/3/dashboard': typeof R3DashboardRoute
  '/3/history': typeof R3HistoryRoute
  '/3/today': typeof R3TodayRoute
  '/4/dashboard': typeof R4DashboardRoute
  '/4/history': typeof R4HistoryRoute
  '/4/today': typeof R4TodayRoute
  '/5/dashboard': typeof R5DashboardRoute
  '/5/history': typeof R5HistoryRoute
  '/5/today': typeof R5TodayRoute
  '/6/dashboard': typeof R6DashboardRoute
  '/6/history': typeof R6HistoryRoute
  '/6/today': typeof R6TodayRoute
  '/7/dashboard': typeof R7DashboardRoute
  '/7/history': typeof R7HistoryRoute
  '/7/today': typeof R7TodayRoute
  '/8/dashboard': typeof R8DashboardRoute
  '/8/history': typeof R8HistoryRoute
  '/8/today': typeof R8TodayRoute
  '/9/dashboard': typeof R9DashboardRoute
  '/9/history': typeof R9HistoryRoute
  '/9/today': typeof R9TodayRoute
  '/1': typeof R1IndexRoute
  '/10': typeof R10IndexRoute
  '/2': typeof R2IndexRoute
  '/3': typeof R3IndexRoute
  '/4': typeof R4IndexRoute
  '/5': typeof R5IndexRoute
  '/6': typeof R6IndexRoute
  '/7': typeof R7IndexRoute
  '/8': typeof R8IndexRoute
  '/9': typeof R9IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/1': typeof R1RouteWithChildren
  '/10': typeof R10RouteWithChildren
  '/11': typeof R11Route
  '/12': typeof R12Route
  '/13': typeof R13Route
  '/14': typeof R14Route
  '/15': typeof R15Route
  '/2': typeof R2RouteWithChildren
  '/3': typeof R3RouteWithChildren
  '/4': typeof R4RouteWithChildren
  '/5': typeof R5RouteWithChildren
  '/6': typeof R6RouteWithChildren
  '/7': typeof R7RouteWithChildren
  '/8': typeof R8RouteWithChildren
  '/9': typeof R9RouteWithChildren
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/1/dashboard': typeof R1DashboardRoute
  '/1/history': typeof R1HistoryRoute
  '/1/today': typeof R1TodayRoute
  '/10/dashboard': typeof R10DashboardRoute
  '/10/history': typeof R10HistoryRoute
  '/10/today': typeof R10TodayRoute
  '/2/dashboard': typeof R2DashboardRoute
  '/2/history': typeof R2HistoryRoute
  '/2/today': typeof R2TodayRoute
  '/3/dashboard': typeof R3DashboardRoute
  '/3/history': typeof R3HistoryRoute
  '/3/today': typeof R3TodayRoute
  '/4/dashboard': typeof R4DashboardRoute
  '/4/history': typeof R4HistoryRoute
  '/4/today': typeof R4TodayRoute
  '/5/dashboard': typeof R5DashboardRoute
  '/5/history': typeof R5HistoryRoute
  '/5/today': typeof R5TodayRoute
  '/6/dashboard': typeof R6DashboardRoute
  '/6/history': typeof R6HistoryRoute
  '/6/today': typeof R6TodayRoute
  '/7/dashboard': typeof R7DashboardRoute
  '/7/history': typeof R7HistoryRoute
  '/7/today': typeof R7TodayRoute
  '/8/dashboard': typeof R8DashboardRoute
  '/8/history': typeof R8HistoryRoute
  '/8/today': typeof R8TodayRoute
  '/9/dashboard': typeof R9DashboardRoute
  '/9/history': typeof R9HistoryRoute
  '/9/today': typeof R9TodayRoute
  '/1/': typeof R1IndexRoute
  '/10/': typeof R10IndexRoute
  '/2/': typeof R2IndexRoute
  '/3/': typeof R3IndexRoute
  '/4/': typeof R4IndexRoute
  '/5/': typeof R5IndexRoute
  '/6/': typeof R6IndexRoute
  '/7/': typeof R7IndexRoute
  '/8/': typeof R8IndexRoute
  '/9/': typeof R9IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/1'
    | '/10'
    | '/11'
    | '/12'
    | '/13'
    | '/14'
    | '/15'
    | '/2'
    | '/3'
    | '/4'
    | '/5'
    | '/6'
    | '/7'
    | '/8'
    | '/9'
    | '/about'
    | '/history'
    | '/1/dashboard'
    | '/1/history'
    | '/1/today'
    | '/10/dashboard'
    | '/10/history'
    | '/10/today'
    | '/2/dashboard'
    | '/2/history'
    | '/2/today'
    | '/3/dashboard'
    | '/3/history'
    | '/3/today'
    | '/4/dashboard'
    | '/4/history'
    | '/4/today'
    | '/5/dashboard'
    | '/5/history'
    | '/5/today'
    | '/6/dashboard'
    | '/6/history'
    | '/6/today'
    | '/7/dashboard'
    | '/7/history'
    | '/7/today'
    | '/8/dashboard'
    | '/8/history'
    | '/8/today'
    | '/9/dashboard'
    | '/9/history'
    | '/9/today'
    | '/1/'
    | '/10/'
    | '/2/'
    | '/3/'
    | '/4/'
    | '/5/'
    | '/6/'
    | '/7/'
    | '/8/'
    | '/9/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/11'
    | '/12'
    | '/13'
    | '/14'
    | '/15'
    | '/about'
    | '/history'
    | '/1/dashboard'
    | '/1/history'
    | '/1/today'
    | '/10/dashboard'
    | '/10/history'
    | '/10/today'
    | '/2/dashboard'
    | '/2/history'
    | '/2/today'
    | '/3/dashboard'
    | '/3/history'
    | '/3/today'
    | '/4/dashboard'
    | '/4/history'
    | '/4/today'
    | '/5/dashboard'
    | '/5/history'
    | '/5/today'
    | '/6/dashboard'
    | '/6/history'
    | '/6/today'
    | '/7/dashboard'
    | '/7/history'
    | '/7/today'
    | '/8/dashboard'
    | '/8/history'
    | '/8/today'
    | '/9/dashboard'
    | '/9/history'
    | '/9/today'
    | '/1'
    | '/10'
    | '/2'
    | '/3'
    | '/4'
    | '/5'
    | '/6'
    | '/7'
    | '/8'
    | '/9'
  id:
    | '__root__'
    | '/'
    | '/1'
    | '/10'
    | '/11'
    | '/12'
    | '/13'
    | '/14'
    | '/15'
    | '/2'
    | '/3'
    | '/4'
    | '/5'
    | '/6'
    | '/7'
    | '/8'
    | '/9'
    | '/about'
    | '/history'
    | '/1/dashboard'
    | '/1/history'
    | '/1/today'
    | '/10/dashboard'
    | '/10/history'
    | '/10/today'
    | '/2/dashboard'
    | '/2/history'
    | '/2/today'
    | '/3/dashboard'
    | '/3/history'
    | '/3/today'
    | '/4/dashboard'
    | '/4/history'
    | '/4/today'
    | '/5/dashboard'
    | '/5/history'
    | '/5/today'
    | '/6/dashboard'
    | '/6/history'
    | '/6/today'
    | '/7/dashboard'
    | '/7/history'
    | '/7/today'
    | '/8/dashboard'
    | '/8/history'
    | '/8/today'
    | '/9/dashboard'
    | '/9/history'
    | '/9/today'
    | '/1/'
    | '/10/'
    | '/2/'
    | '/3/'
    | '/4/'
    | '/5/'
    | '/6/'
    | '/7/'
    | '/8/'
    | '/9/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R1Route: typeof R1RouteWithChildren
  R10Route: typeof R10RouteWithChildren
  R11Route: typeof R11Route
  R12Route: typeof R12Route
  R13Route: typeof R13Route
  R14Route: typeof R14Route
  R15Route: typeof R15Route
  R2Route: typeof R2RouteWithChildren
  R3Route: typeof R3RouteWithChildren
  R4Route: typeof R4RouteWithChildren
  R5Route: typeof R5RouteWithChildren
  R6Route: typeof R6RouteWithChildren
  R7Route: typeof R7RouteWithChildren
  R8Route: typeof R8RouteWithChildren
  R9Route: typeof R9RouteWithChildren
  AboutRoute: typeof AboutRoute
  HistoryRoute: typeof HistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/9': {
      id: '/9'
      path: '/9'
      fullPath: '/9'
      preLoaderRoute: typeof R9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/8': {
      id: '/8'
      path: '/8'
      fullPath: '/8'
      preLoaderRoute: typeof R8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/7': {
      id: '/7'
      path: '/7'
      fullPath: '/7'
      preLoaderRoute: typeof R7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/6': {
      id: '/6'
      path: '/6'
      fullPath: '/6'
      preLoaderRoute: typeof R6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/5': {
      id: '/5'
      path: '/5'
      fullPath: '/5'
      preLoaderRoute: typeof R5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/4': {
      id: '/4'
      path: '/4'
      fullPath: '/4'
      preLoaderRoute: typeof R4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3': {
      id: '/3'
      path: '/3'
      fullPath: '/3'
      preLoaderRoute: typeof R3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2': {
      id: '/2'
      path: '/2'
      fullPath: '/2'
      preLoaderRoute: typeof R2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/15': {
      id: '/15'
      path: '/15'
      fullPath: '/15'
      preLoaderRoute: typeof R15RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/14': {
      id: '/14'
      path: '/14'
      fullPath: '/14'
      preLoaderRoute: typeof R14RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/13': {
      id: '/13'
      path: '/13'
      fullPath: '/13'
      preLoaderRoute: typeof R13RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/12': {
      id: '/12'
      path: '/12'
      fullPath: '/12'
      preLoaderRoute: typeof R12RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/11': {
      id: '/11'
      path: '/11'
      fullPath: '/11'
      preLoaderRoute: typeof R11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/10': {
      id: '/10'
      path: '/10'
      fullPath: '/10'
      preLoaderRoute: typeof R10RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/1': {
      id: '/1'
      path: '/1'
      fullPath: '/1'
      preLoaderRoute: typeof R1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/9/': {
      id: '/9/'
      path: '/'
      fullPath: '/9/'
      preLoaderRoute: typeof R9IndexRouteImport
      parentRoute: typeof R9Route
    }
    '/8/': {
      id: '/8/'
      path: '/'
      fullPath: '/8/'
      preLoaderRoute: typeof R8IndexRouteImport
      parentRoute: typeof R8Route
    }
    '/7/': {
      id: '/7/'
      path: '/'
      fullPath: '/7/'
      preLoaderRoute: typeof R7IndexRouteImport
      parentRoute: typeof R7Route
    }
    '/6/': {
      id: '/6/'
      path: '/'
      fullPath: '/6/'
      preLoaderRoute: typeof R6IndexRouteImport
      parentRoute: typeof R6Route
    }
    '/5/': {
      id: '/5/'
      path: '/'
      fullPath: '/5/'
      preLoaderRoute: typeof R5IndexRouteImport
      parentRoute: typeof R5Route
    }
    '/4/': {
      id: '/4/'
      path: '/'
      fullPath: '/4/'
      preLoaderRoute: typeof R4IndexRouteImport
      parentRoute: typeof R4Route
    }
    '/3/': {
      id: '/3/'
      path: '/'
      fullPath: '/3/'
      preLoaderRoute: typeof R3IndexRouteImport
      parentRoute: typeof R3Route
    }
    '/2/': {
      id: '/2/'
      path: '/'
      fullPath: '/2/'
      preLoaderRoute: typeof R2IndexRouteImport
      parentRoute: typeof R2Route
    }
    '/10/': {
      id: '/10/'
      path: '/'
      fullPath: '/10/'
      preLoaderRoute: typeof R10IndexRouteImport
      parentRoute: typeof R10Route
    }
    '/1/': {
      id: '/1/'
      path: '/'
      fullPath: '/1/'
      preLoaderRoute: typeof R1IndexRouteImport
      parentRoute: typeof R1Route
    }
    '/9/today': {
      id: '/9/today'
      path: '/today'
      fullPath: '/9/today'
      preLoaderRoute: typeof R9TodayRouteImport
      parentRoute: typeof R9Route
    }
    '/9/history': {
      id: '/9/history'
      path: '/history'
      fullPath: '/9/history'
      preLoaderRoute: typeof R9HistoryRouteImport
      parentRoute: typeof R9Route
    }
    '/9/dashboard': {
      id: '/9/dashboard'
      path: '/dashboard'
      fullPath: '/9/dashboard'
      preLoaderRoute: typeof R9DashboardRouteImport
      parentRoute: typeof R9Route
    }
    '/8/today': {
      id: '/8/today'
      path: '/today'
      fullPath: '/8/today'
      preLoaderRoute: typeof R8TodayRouteImport
      parentRoute: typeof R8Route
    }
    '/8/history': {
      id: '/8/history'
      path: '/history'
      fullPath: '/8/history'
      preLoaderRoute: typeof R8HistoryRouteImport
      parentRoute: typeof R8Route
    }
    '/8/dashboard': {
      id: '/8/dashboard'
      path: '/dashboard'
      fullPath: '/8/dashboard'
      preLoaderRoute: typeof R8DashboardRouteImport
      parentRoute: typeof R8Route
    }
    '/7/today': {
      id: '/7/today'
      path: '/today'
      fullPath: '/7/today'
      preLoaderRoute: typeof R7TodayRouteImport
      parentRoute: typeof R7Route
    }
    '/7/history': {
      id: '/7/history'
      path: '/history'
      fullPath: '/7/history'
      preLoaderRoute: typeof R7HistoryRouteImport
      parentRoute: typeof R7Route
    }
    '/7/dashboard': {
      id: '/7/dashboard'
      path: '/dashboard'
      fullPath: '/7/dashboard'
      preLoaderRoute: typeof R7DashboardRouteImport
      parentRoute: typeof R7Route
    }
    '/6/today': {
      id: '/6/today'
      path: '/today'
      fullPath: '/6/today'
      preLoaderRoute: typeof R6TodayRouteImport
      parentRoute: typeof R6Route
    }
    '/6/history': {
      id: '/6/history'
      path: '/history'
      fullPath: '/6/history'
      preLoaderRoute: typeof R6HistoryRouteImport
      parentRoute: typeof R6Route
    }
    '/6/dashboard': {
      id: '/6/dashboard'
      path: '/dashboard'
      fullPath: '/6/dashboard'
      preLoaderRoute: typeof R6DashboardRouteImport
      parentRoute: typeof R6Route
    }
    '/5/today': {
      id: '/5/today'
      path: '/today'
      fullPath: '/5/today'
      preLoaderRoute: typeof R5TodayRouteImport
      parentRoute: typeof R5Route
    }
    '/5/history': {
      id: '/5/history'
      path: '/history'
      fullPath: '/5/history'
      preLoaderRoute: typeof R5HistoryRouteImport
      parentRoute: typeof R5Route
    }
    '/5/dashboard': {
      id: '/5/dashboard'
      path: '/dashboard'
      fullPath: '/5/dashboard'
      preLoaderRoute: typeof R5DashboardRouteImport
      parentRoute: typeof R5Route
    }
    '/4/today': {
      id: '/4/today'
      path: '/today'
      fullPath: '/4/today'
      preLoaderRoute: typeof R4TodayRouteImport
      parentRoute: typeof R4Route
    }
    '/4/history': {
      id: '/4/history'
      path: '/history'
      fullPath: '/4/history'
      preLoaderRoute: typeof R4HistoryRouteImport
      parentRoute: typeof R4Route
    }
    '/4/dashboard': {
      id: '/4/dashboard'
      path: '/dashboard'
      fullPath: '/4/dashboard'
      preLoaderRoute: typeof R4DashboardRouteImport
      parentRoute: typeof R4Route
    }
    '/3/today': {
      id: '/3/today'
      path: '/today'
      fullPath: '/3/today'
      preLoaderRoute: typeof R3TodayRouteImport
      parentRoute: typeof R3Route
    }
    '/3/history': {
      id: '/3/history'
      path: '/history'
      fullPath: '/3/history'
      preLoaderRoute: typeof R3HistoryRouteImport
      parentRoute: typeof R3Route
    }
    '/3/dashboard': {
      id: '/3/dashboard'
      path: '/dashboard'
      fullPath: '/3/dashboard'
      preLoaderRoute: typeof R3DashboardRouteImport
      parentRoute: typeof R3Route
    }
    '/2/today': {
      id: '/2/today'
      path: '/today'
      fullPath: '/2/today'
      preLoaderRoute: typeof R2TodayRouteImport
      parentRoute: typeof R2Route
    }
    '/2/history': {
      id: '/2/history'
      path: '/history'
      fullPath: '/2/history'
      preLoaderRoute: typeof R2HistoryRouteImport
      parentRoute: typeof R2Route
    }
    '/2/dashboard': {
      id: '/2/dashboard'
      path: '/dashboard'
      fullPath: '/2/dashboard'
      preLoaderRoute: typeof R2DashboardRouteImport
      parentRoute: typeof R2Route
    }
    '/10/today': {
      id: '/10/today'
      path: '/today'
      fullPath: '/10/today'
      preLoaderRoute: typeof R10TodayRouteImport
      parentRoute: typeof R10Route
    }
    '/10/history': {
      id: '/10/history'
      path: '/history'
      fullPath: '/10/history'
      preLoaderRoute: typeof R10HistoryRouteImport
      parentRoute: typeof R10Route
    }
    '/10/dashboard': {
      id: '/10/dashboard'
      path: '/dashboard'
      fullPath: '/10/dashboard'
      preLoaderRoute: typeof R10DashboardRouteImport
      parentRoute: typeof R10Route
    }
    '/1/today': {
      id: '/1/today'
      path: '/today'
      fullPath: '/1/today'
      preLoaderRoute: typeof R1TodayRouteImport
      parentRoute: typeof R1Route
    }
    '/1/history': {
      id: '/1/history'
      path: '/history'
      fullPath: '/1/history'
      preLoaderRoute: typeof R1HistoryRouteImport
      parentRoute: typeof R1Route
    }
    '/1/dashboard': {
      id: '/1/dashboard'
      path: '/dashboard'
      fullPath: '/1/dashboard'
      preLoaderRoute: typeof R1DashboardRouteImport
      parentRoute: typeof R1Route
    }
  }
}

interface R1RouteChildren {
  R1DashboardRoute: typeof R1DashboardRoute
  R1HistoryRoute: typeof R1HistoryRoute
  R1TodayRoute: typeof R1TodayRoute
  R1IndexRoute: typeof R1IndexRoute
}

const R1RouteChildren: R1RouteChildren = {
  R1DashboardRoute: R1DashboardRoute,
  R1HistoryRoute: R1HistoryRoute,
  R1TodayRoute: R1TodayRoute,
  R1IndexRoute: R1IndexRoute,
}

const R1RouteWithChildren = R1Route._addFileChildren(R1RouteChildren)

interface R10RouteChildren {
  R10DashboardRoute: typeof R10DashboardRoute
  R10HistoryRoute: typeof R10HistoryRoute
  R10TodayRoute: typeof R10TodayRoute
  R10IndexRoute: typeof R10IndexRoute
}

const R10RouteChildren: R10RouteChildren = {
  R10DashboardRoute: R10DashboardRoute,
  R10HistoryRoute: R10HistoryRoute,
  R10TodayRoute: R10TodayRoute,
  R10IndexRoute: R10IndexRoute,
}

const R10RouteWithChildren = R10Route._addFileChildren(R10RouteChildren)

interface R2RouteChildren {
  R2DashboardRoute: typeof R2DashboardRoute
  R2HistoryRoute: typeof R2HistoryRoute
  R2TodayRoute: typeof R2TodayRoute
  R2IndexRoute: typeof R2IndexRoute
}

const R2RouteChildren: R2RouteChildren = {
  R2DashboardRoute: R2DashboardRoute,
  R2HistoryRoute: R2HistoryRoute,
  R2TodayRoute: R2TodayRoute,
  R2IndexRoute: R2IndexRoute,
}

const R2RouteWithChildren = R2Route._addFileChildren(R2RouteChildren)

interface R3RouteChildren {
  R3DashboardRoute: typeof R3DashboardRoute
  R3HistoryRoute: typeof R3HistoryRoute
  R3TodayRoute: typeof R3TodayRoute
  R3IndexRoute: typeof R3IndexRoute
}

const R3RouteChildren: R3RouteChildren = {
  R3DashboardRoute: R3DashboardRoute,
  R3HistoryRoute: R3HistoryRoute,
  R3TodayRoute: R3TodayRoute,
  R3IndexRoute: R3IndexRoute,
}

const R3RouteWithChildren = R3Route._addFileChildren(R3RouteChildren)

interface R4RouteChildren {
  R4DashboardRoute: typeof R4DashboardRoute
  R4HistoryRoute: typeof R4HistoryRoute
  R4TodayRoute: typeof R4TodayRoute
  R4IndexRoute: typeof R4IndexRoute
}

const R4RouteChildren: R4RouteChildren = {
  R4DashboardRoute: R4DashboardRoute,
  R4HistoryRoute: R4HistoryRoute,
  R4TodayRoute: R4TodayRoute,
  R4IndexRoute: R4IndexRoute,
}

const R4RouteWithChildren = R4Route._addFileChildren(R4RouteChildren)

interface R5RouteChildren {
  R5DashboardRoute: typeof R5DashboardRoute
  R5HistoryRoute: typeof R5HistoryRoute
  R5TodayRoute: typeof R5TodayRoute
  R5IndexRoute: typeof R5IndexRoute
}

const R5RouteChildren: R5RouteChildren = {
  R5DashboardRoute: R5DashboardRoute,
  R5HistoryRoute: R5HistoryRoute,
  R5TodayRoute: R5TodayRoute,
  R5IndexRoute: R5IndexRoute,
}

const R5RouteWithChildren = R5Route._addFileChildren(R5RouteChildren)

interface R6RouteChildren {
  R6DashboardRoute: typeof R6DashboardRoute
  R6HistoryRoute: typeof R6HistoryRoute
  R6TodayRoute: typeof R6TodayRoute
  R6IndexRoute: typeof R6IndexRoute
}

const R6RouteChildren: R6RouteChildren = {
  R6DashboardRoute: R6DashboardRoute,
  R6HistoryRoute: R6HistoryRoute,
  R6TodayRoute: R6TodayRoute,
  R6IndexRoute: R6IndexRoute,
}

const R6RouteWithChildren = R6Route._addFileChildren(R6RouteChildren)

interface R7RouteChildren {
  R7DashboardRoute: typeof R7DashboardRoute
  R7HistoryRoute: typeof R7HistoryRoute
  R7TodayRoute: typeof R7TodayRoute
  R7IndexRoute: typeof R7IndexRoute
}

const R7RouteChildren: R7RouteChildren = {
  R7DashboardRoute: R7DashboardRoute,
  R7HistoryRoute: R7HistoryRoute,
  R7TodayRoute: R7TodayRoute,
  R7IndexRoute: R7IndexRoute,
}

const R7RouteWithChildren = R7Route._addFileChildren(R7RouteChildren)

interface R8RouteChildren {
  R8DashboardRoute: typeof R8DashboardRoute
  R8HistoryRoute: typeof R8HistoryRoute
  R8TodayRoute: typeof R8TodayRoute
  R8IndexRoute: typeof R8IndexRoute
}

const R8RouteChildren: R8RouteChildren = {
  R8DashboardRoute: R8DashboardRoute,
  R8HistoryRoute: R8HistoryRoute,
  R8TodayRoute: R8TodayRoute,
  R8IndexRoute: R8IndexRoute,
}

const R8RouteWithChildren = R8Route._addFileChildren(R8RouteChildren)

interface R9RouteChildren {
  R9DashboardRoute: typeof R9DashboardRoute
  R9HistoryRoute: typeof R9HistoryRoute
  R9TodayRoute: typeof R9TodayRoute
  R9IndexRoute: typeof R9IndexRoute
}

const R9RouteChildren: R9RouteChildren = {
  R9DashboardRoute: R9DashboardRoute,
  R9HistoryRoute: R9HistoryRoute,
  R9TodayRoute: R9TodayRoute,
  R9IndexRoute: R9IndexRoute,
}

const R9RouteWithChildren = R9Route._addFileChildren(R9RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R1Route: R1RouteWithChildren,
  R10Route: R10RouteWithChildren,
  R11Route: R11Route,
  R12Route: R12Route,
  R13Route: R13Route,
  R14Route: R14Route,
  R15Route: R15Route,
  R2Route: R2RouteWithChildren,
  R3Route: R3RouteWithChildren,
  R4Route: R4RouteWithChildren,
  R5Route: R5RouteWithChildren,
  R6Route: R6RouteWithChildren,
  R7Route: R7RouteWithChildren,
  R8Route: R8RouteWithChildren,
  R9Route: R9RouteWithChildren,
  AboutRoute: AboutRoute,
  HistoryRoute: HistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
